### ISSUE TITLE
Lovalace forked daapd card is not working

### ISSUE THREAD

**Issue by stlas** [kalkih/forked-daapd-card#1]
Hi, 
my server is up and running, works well in the browser. The code on top of ui-lovelace.yaml is:
`  - url: /local/forked-daapd-card.js?v=0.8.3
    type: module `
and below:
`      - type: custom:forked-daapd-card
        entity: media_player.mpd
        ip: 192.168.178.$$$
        port: 3689
        name: Multiroom `
The result is:
![screenshot 23](https://user-images.githubusercontent.com/35530959/47255334-bf418280-d46f-11e8-9fc8-0c0a28a8bdd1.jpg)
Thanx for your help.
Stefan

**Comment by stlas** [comment]
Sorry, i inserted it as "code" but the newlines are gone...

**Comment by kalkih** [comment]
Seems like the mpd media player is unavailable.
Does your `media_player.mpd` work if you set it up as a normal media-control card? Or does it still show up as unavailable?

```yaml
- entity: media_player.mpd
  type: media-control
```

**Comment by stlas** [comment]
You are right. In the states it shows:
`
media_player.mpd | unavailable | friendly_name: MPD
`
In the configuration.yaml:

```
media_player:
  - platform: mpd
    host: 192.168.178.$$$

```

**Comment by kalkih** [comment]
Yes, that's the issue, make sure you set up your forked daapd in home assistant properly.

**Comment by kalkih** [comment]
@stlas Did you get it working?
