### ISSUE TITLE
custom element doesn't exist

### ISSUE THREAD

**Issue by snizzleorg** [kalkih/forked-daapd-card#2]
I have your card configured as described but unfortunately I get Customer element does not exist. Since it's v0.0.1 - is this expected to work already?

would be awesome!

**Comment by kalkih** [comment]
Hey,
Yes it's supposed to work, however there's a problem with the external dependency at the moment, I will fix this later tonight and get back to you.
Thank you.

**Comment by kalkih** [comment]
@snizzleorg I just released a new version [v0.0.2](https://github.com/kalkih/forked-daapd-card/releases/tag/v0.0.2) with a fix for this issue.
Thanks!

**Comment by snizzleorg** [comment]
Thanks for an amazing card!
