### ISSUE TITLE
Missing info on card

### ISSUE THREAD

**Issue by RienduPre** [kalkih/forked-daapd-card#5]
Hi,

I implemnted your forked-daapd Lovelace card, but it seems to miss some info/functions (see screenshot)
<img width="484" alt="Schermafbeelding 2020-09-25 om 16 34 51" src="https://user-images.githubusercontent.com/9009949/94345625-8cbf3d80-0027-11eb-9410-3aaee5a158f6.png">

I run the the latest version of all related software....

Thanks,
Rien

**Comment by squireblackdens** [comment]
Exact same problem here.

**Comment by uchagani** [comment]
@kalkih it seems that the `<paper-icon-button>` elements are not showing up.  they are still clickable but they are hidden.  See image:

<img width="421" alt="image" src="https://user-images.githubusercontent.com/1053584/102845064-b5629380-43da-11eb-9079-5800e13c8bbf.png">

**Comment by uchagani** [comment]
@RienduPre @squireblackdens  this issue is fixed with #7
