### ISSUE TITLE
Allow setting Name of output

### ISSUE THREAD

**Issue by uchagani** [kalkih/forked-daapd-card#6]
I have multiple output devices in the same room and they show up like this:

<img width="369" alt="image" src="https://user-images.githubusercontent.com/1053584/102845125-d7f4ac80-43da-11eb-9c9f-b168656e8b1f.png">

It would be nice if I could change the name of them so I don't have to remember which one `Living Room (2)` is.

**Comment by kimme1024** [comment]
Also looking for this option.
Did you implement this this?
If yes, how can I change them?
